import { NgModule } from '@angular/core';
import {
    MatButtonModule,
    MatIconModule,
    MatListModule,
    MatTooltipModule,
    MatTabsModule,
    MatMenuModule,
    MatCheckboxModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatAutocompleteModule,
    MatSelectModule,
    MatTableModule,
    MatBottomSheetModule,
    MatSnackBarModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatGridListModule,
    MatToolbarModule,
    MatProgressBarModule,
    MatPaginatorModule,
    MatSortModule,
    MatCardModule,

} from '@angular/material';

@NgModule({
    imports: [
        // Material
        MatButtonModule,
        MatIconModule,
        MatListModule,
        MatTooltipModule,
        MatTabsModule,
        MatMenuModule,
        MatCheckboxModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatInputModule,
        MatDatepickerModule,
        MatAutocompleteModule,
        MatSelectModule,
        MatTableModule,
        MatBottomSheetModule,
        MatSnackBarModule,
        MatDialogModule,
        MatProgressSpinnerModule,
        MatChipsModule,
        MatGridListModule,
        MatToolbarModule,
        MatProgressBarModule,
        MatPaginatorModule,
        MatSortModule,
        MatCardModule,
    ],
    exports: [
        // Material
        MatButtonModule,
        MatIconModule,
        MatListModule,
        MatTooltipModule,
        MatTabsModule,
        MatMenuModule,
        MatCheckboxModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatInputModule,
        MatDatepickerModule,
        MatAutocompleteModule,
        MatSelectModule,
        MatTableModule,
        MatBottomSheetModule,
        MatSnackBarModule,
        MatDialogModule,
        MatProgressSpinnerModule,
        MatChipsModule,
        MatGridListModule,
        MatToolbarModule,
        MatProgressBarModule,
        MatPaginatorModule,
        MatSortModule,
        MatCardModule,

    ]
})
export class SharedMaterialModule {}
